[package]
name = "ml-core"
version = "0.1.0"
edition = "2024"

[features]
default = []
with-tch = ["tch", "image"]

[dependencies]
tch = { version = "0.18", optional = true }
image = { version = "0.25.8", default-features = false, features = ["png", "jpeg"], optional = true }
