[package]
name = "viz"
edition.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
bevy = "0.17.1"
image = { version = "0.25.8", features = ["jpeg"] }
reqwest = { version = "0.12.23", features = ["blocking", "rustls-tls"] }
